export const COUNTRY_CONFIG: Record<string, { name: string; brandName: string; subdomain: string }> = {
  NG: { name: 'Nigeria', brandName: 'Nigeria', subdomain: 'ng' },
  GH: { name: 'Ghana', brandName: 'Ghana', subdomain: 'gh' },
  KE: { name: 'Kenya', brandName: 'Kenya', subdomain: 'ke' },
  ZA: { name: 'South Africa', brandName: 'South Africa', subdomain: 'za' },
  UG: { name: 'Uganda', brandName: 'Uganda', subdomain: 'ug' },
  RW: { name: 'Rwanda', brandName: 'Rwanda', subdomain: 'rw' },
  TZ: { name: 'Tanzania', brandName: 'Tanzania', subdomain: 'tz' },
  ET: { name: 'Ethiopia', brandName: 'Ethiopia', subdomain: 'et' },
  SN: { name: 'Senegal', brandName: 'Senegal', subdomain: 'sn' },
  CM: { name: 'Cameroon', brandName: 'Cameroon', subdomain: 'cm' },
  EG: { name: 'Egypt', brandName: 'Egypt', subdomain: 'eg' },
  MA: { name: 'Morocco', brandName: 'Morocco', subdomain: 'ma' },
  DZ: { name: 'Algeria', brandName: 'Algeria', subdomain: 'dz' },
  TN: { name: 'Tunisia', brandName: 'Tunisia', subdomain: 'tn' },
  CI: { name: "Côte d'Ivoire", brandName: "Côte d'Ivoire", subdomain: 'ci' },
  AO: { name: 'Angola', brandName: 'Angola', subdomain: 'ao' },
  MZ: { name: 'Mozambique', brandName: 'Mozambique', subdomain: 'mz' },
  CD: { name: 'DR Congo', brandName: 'DR Congo', subdomain: 'cd' },
  SD: { name: 'Sudan', brandName: 'Sudan', subdomain: 'sd' },
  LY: { name: 'Libya', brandName: 'Libya', subdomain: 'ly' },
  ZW: { name: 'Zimbabwe', brandName: 'Zimbabwe', subdomain: 'zw' },
  ZM: { name: 'Zambia', brandName: 'Zambia', subdomain: 'zm' },
  MW: { name: 'Malawi', brandName: 'Malawi', subdomain: 'mw' },
  BJ: { name: 'Benin', brandName: 'Benin', subdomain: 'bj' },
  TG: { name: 'Togo', brandName: 'Togo', subdomain: 'tg' },
  ML: { name: 'Mali', brandName: 'Mali', subdomain: 'ml' },
  BF: { name: 'Burkina Faso', brandName: 'Burkina Faso', subdomain: 'bf' },
  NE: { name: 'Niger', brandName: 'Niger', subdomain: 'ne' },
  SL: { name: 'Sierra Leone', brandName: 'Sierra Leone', subdomain: 'sl' },
  LR: { name: 'Liberia', brandName: 'Liberia', subdomain: 'lr' },
  SO: { name: 'Somalia', brandName: 'Somalia', subdomain: 'so' },
  MG: { name: 'Madagascar', brandName: 'Madagascar', subdomain: 'mg' },
};

export const REPORT_CATEGORY_LABELS: Record<string, string> = {
  traffic: 'Traffic Report',
  police_security: 'Police & Security',
  government: 'Government Accountability',
  construction: 'Construction & Infrastructure',
  election: 'Election & Voting',
  emergency: 'Community Emergency',
  environmental: 'Environmental',
  market_consumer: 'Market & Consumer',
};
